### ISSUE TITLE
Confluence Swagger Add-ons : Location of plugin logs or connection logs

### ISSUE THREAD

**Issue by Mayur-Ingale** [toshihirosatojp/swagger-ui#1]
Hi Team,

We are planning to purchase this add-on. Testing is going on our test server.

Developer has found some issues. When they tried to execute call to our AWS sandbox account they get "type error - failed to fetch" (running the same request from a browser or any other client works)

Could you please let us know what is the location of Swagger plugin logs or connection logs or something similar.

**Comment by toshihirosatojp** [comment]
Hi @Mayur-Ingale , maybe you got CORS policy error. You need to configure your server to return correct policy. 
Thank you very much!
