### ISSUE TITLE
Several Swagger macro in the same confluence Page

### ISSUE THREAD

**Issue by alexliaut** [toshihirosatojp/swagger-ui#2]
Hello, 

We are very interesting by your plugin. However, we would like to add Several Swagger macro in the same confluence Page to describe and structure our interface specification. We tested your plugin (trial version) few weeks ago and we can add only one macro by page. 
Do you plan this feature in a new release or not? Maybe, it 's possible and we don't use correctly your plugin.

Thanks a lot

**Comment by rkrauklis** [comment]
I am also running the trial version and I have the exact same question:  Is it possible to add more than one Open API macro to a page?

**Comment by toshihirosatojp** [comment]
Hi @alexliaut & @rkrauklis , 
Thank you very much for your request! Currently we use Swagger UI as the core of our plugin and we see that it is not support well to display several Swagger document on a page. We'll research more on this function and let you know soon!

**Comment by toshihirosatojp** [comment]
We have just released a new version which support this request.
Please update to the latest version!
