### ISSUE TITLE
Can't paste markup

### ISSUE THREAD

**Issue by eeromay** [toshihirosatojp/swagger-ui#7]
We didn't host our open api definitions on our server.
In your documentation you say it can be posted into the body.

But if we post the yaml or json markup (we took the swagger petstore example) the app shows the error: No API definition provided.

What we do wrong?

![screenshot](https://user-images.githubusercontent.com/56441202/81946161-4d0b3280-95ff-11ea-89cf-7a2d834f063b.png)

**Comment by toshihirosatojp** [comment]
Hi @eeromay, 
You need to save the page so it can display correctly.
Best regards,
Toshihiro Sato

**Comment by toshihirosatojp** [comment]
Hi @eeromay, 
We have updated our app so it will show a more correctly message.
Best regards,
Toshi Sato
